# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pm < Formula
  desc "CLI tool for managing project runbooks from .pm/ directories"
  homepage "https://github.com/hojooneum/pm"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/minusmo/pm/releases/download/v0.4.0/pm_0.4.0_darwin_amd64.tar.gz"
      sha256 "cff85c5e49abced2d956c03affa677c6a393a09af1a7bb5678251a1484907fda"

      def install
        bin.install "pm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/minusmo/pm/releases/download/v0.4.0/pm_0.4.0_darwin_arm64.tar.gz"
      sha256 "4113a0f5615d5868a80d488e1465596364a83a3f1349b4817c60e927f16e1327"

      def install
        bin.install "pm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/minusmo/pm/releases/download/v0.4.0/pm_0.4.0_linux_amd64.tar.gz"
      sha256 "e078aa2352dc74e6ee454d8618b3a32efa29c927a4d9c656c8f7408004d78226"
      def install
        bin.install "pm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/minusmo/pm/releases/download/v0.4.0/pm_0.4.0_linux_arm64.tar.gz"
      sha256 "dd528731c5ebe76a2f3578fe22044c1f8f861c923d2d2627fa9595a8400ea281"
      def install
        bin.install "pm"
      end
    end
  end

  test do
    system "#{bin}/pm", "--version"
  end
end
