# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pm < Formula
  desc "CLI tool for managing project runbooks from .pm/ directories"
  homepage "https://github.com/hojooneum/pm"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/minusmo/pm/releases/download/v0.3.1/pm_0.3.1_darwin_amd64.tar.gz"
      sha256 "d60ddd6a5f1a80cbe05027e32a54e4fba7aef8b0c409f494151479cfd215a1be"

      def install
        bin.install "pm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/minusmo/pm/releases/download/v0.3.1/pm_0.3.1_darwin_arm64.tar.gz"
      sha256 "cc62ccdd5b3e30fe3706bdc44ca0267c86348b9d580d488e3a4865f28344147b"

      def install
        bin.install "pm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/minusmo/pm/releases/download/v0.3.1/pm_0.3.1_linux_amd64.tar.gz"
      sha256 "6495b50c9f77cf214f8583aecf4ef9a309bbd7c525b8e88008bf5d9766261b9f"
      def install
        bin.install "pm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/minusmo/pm/releases/download/v0.3.1/pm_0.3.1_linux_arm64.tar.gz"
      sha256 "d85bcffd82615af84d93fb4ed27e9248896c63dcc33e1475fb9ca993ef4c9047"
      def install
        bin.install "pm"
      end
    end
  end

  test do
    system "#{bin}/pm", "--version"
  end
end
